name: pocket
version: 0.2.0

synopsis: Bindings for the Pocket API
description: Bindings for the Pocket API.

category: Web

author: Juan Pedro Villa Isaza

github: jpvillaisaza/pocket-haskell

license-file: LICENSE.md

library:
  source-dirs: src
  other-modules:
    - Web.Pocket.Request
  dependencies:
    - aeson
    - base >= 4.13 && < 4.14
    - bytestring
    - exceptions
    - http-conduit >= 2.3
    - http-types
    - text
  ghc-options:
    - -Wall
